services:
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
      - "29093:29093"
    volumes:
      - kafka-validation-data:/var/lib/kafka/data
    environment:
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_LISTENERS: "PLAINTEXT_HOST://0.0.0.0:9092,PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT_HOST://localhost:9092,PLAINTEXT://kafka:29092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      # ---- Storage ----
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      CLUSTER_ID: "C-1Pn8WSTOamp-3aPkhjGQ"
    command:
      - bash
      - -c
      - |
        # Start Kafka in background
        /etc/confluent/docker/run &
        
        # Wait for Kafka to be ready
        # echo "Waiting for Kafka to start..."
        # cub kafka-ready -b localhost:9092 1 60
        
        echo 'Waiting for Kafka broker...';
        until kafka-broker-api-versions --bootstrap-server kafka:29092 > /dev/null 2>&1; do
          sleep 2;
        done;
        
        # Create topics
        echo "Creating Kafka topics..."
        kafka-topics --bootstrap-server localhost:9092 --create --if-not-exists --topic raw-trades-topic --partitions 2 --replication-factor 1
        kafka-topics --bootstrap-server localhost:9092 --create --if-not-exists --topic valid-trades-topic --partitions 2 --replication-factor 1
        kafka-topics --bootstrap-server localhost:9092 --create --if-not-exists --topic invalid-trades-topic --partitions 2 --replication-factor 1
        kafka-topics --bootstrap-server localhost:9092 --create --if-not-exists --topic rttm.trade.events --partitions 2 --replication-factor 1
        kafka-topics --bootstrap-server localhost:9092 --create --if-not-exists --topic rttm.dlq.events --partitions 2 --replication-factor 1
        kafka-topics --bootstrap-server localhost:9092 --create --if-not-exists --topic rttm.queue.metrics --partitions 2 --replication-factor 1
        kafka-topics --bootstrap-server localhost:9092 --create --if-not-exists --topic rttm.error.events --partitions 2 --replication-factor 1
        kafka-topics --bootstrap-server localhost:9092 --create --if-not-exists --topic _schemas --partitions 1 --replication-factor 1 --config cleanup.policy=compact
        
        echo "Topics created successfully!"
        
        # Keep container running
        wait


  schema-registry:
    image: confluentinc/cp-schema-registry:7.6.0
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka:29092"
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.6.0
    hostname: control-center
    container_name: control-center
    depends_on:
      - kafka
      - schema-registry
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka:29092"
      CONTROL_CENTER_SCHEMA_REGISTRY_URLS: "http://schema-registry:8081"
      CONTROL_CENTER_CONNECT_CLUSTER: ""
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_INTERNAL_TOPICS_REPLICATION: 1
      PORT: 9021

  redis:
    image: "redislabs/redismod"
    hostname: redis
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    entrypoint: >
      redis-server
        --loadmodule /usr/lib/redis/modules/redisai.so
          ONNX redisai_onnxruntime/redisai_onnxruntime.so
          TF redisai_tensorflow/redisai_tensorflow.so
          TFLITE redisai_tflite/redisai_tflite.so
          TORCH redisai_torch/redisai_torch.so   
        --loadmodule /usr/lib/redis/modules/redisearch.so
        --loadmodule /usr/lib/redis/modules/redisgraph.so
        --loadmodule /usr/lib/redis/modules/redistimeseries.so
        --loadmodule /usr/lib/redis/modules/rejson.so
        --loadmodule /usr/lib/redis/modules/redisbloom.so
        --loadmodule /usr/lib/redis/modules/redisgears.so
        --appendonly yes
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  kafka-validation-data:
  # validation-service:
  #   build:
  #     context: ..
  #     dockerfile: docker/Dockerfile
  #   container_name: validation-service
  #   depends_on:
  #     - kafka
  #     - redis
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     KAFKA_BOOTSTRAP_SERVERS: "kafka:29092"
  #     REDIS_HOST: "redis"
  #     REDIS_PORT: "6379"
  #     DB_URL: "jdbc:postgresql://your-db-host:5432/your-db-name"
  #     DB_USERNAME: "your-db-user"
  #     DB_PASSWORD: "your-db-password"
  #     KAFKA_CONSUMER_GROUP_ID: "validation-group"
  #     SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
  #     INCOMING_TRADES_TOPIC: "raw-trades-topic"
  #     OUTGOING_VALID_TRADES_TOPIC: "valid-trades-topic"
  #     OUTGOING_INVALID_TRADES_TOPIC: "invalid-trades-topic"
  #   networks:
  #     - default